spring:
  profiles:
    active: ${SPRING_PROFILE:local}

server:
  port: ${BILLING_SERVICE_PORT:8084}

---
spring:
  r2dbc:
    url: r2dbc:pool:postgresql://${POSTGRES_SHIPPING_URL}/shipping
    username: postgres
    password: ${POSTGRES_SHIPPING_PWD}
    initialization-mode: always
    pool:
      initial-size: 10
      max-size: 30
      max-idle-time: 30m

logging:
  level:
    org.springframework.r2dbc: ${SPRING_R2DBC_LOGGING_LEVEL:DEBUG}
    io.r2dbc.postgresql.QUERY: ${POSTGRES_QUERY_LOGGING_LEVEL:DEBUG}
    io.r2dbc.postgresql.PARAM: ${POSTGRES_PARAM_LOGGING_LEVEL:DEBUG}
