spring:
  profiles:
    active: ${SPRING_PROFILE:local}

---
spring:
  r2dbc:
    url: r2dbc:pool:postgresql://${POSTGRES_SHIPPING_URL}/shipping
    username: postgres
    password: ${POSTGRES_SHIPPING_PWD}
    initialization-mode: always
    pool:
      initial-size: 10
      max-size: 30
      max-idle-time: 30m

logging:
  level:
    org.springframework.data.r2dbc: ${LOGGING_LEVEL:DEBUG}
