spring:
  profiles:
    active: ${SPRING_PROFILE:local}

---
spring:
  r2dbc:
    url: r2dbc:pool:postgresql://${POSTGRES_CUSTOMER_URL}/customer
    username: postgres
    password: ${POSTGRES_CUSTOMER_PWD}
    initialization-mode: always
    pool:
      initial-size: 10
      max-size: 30
      max-idle-time: 30m
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_HOST}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


logging:
  level:
    org.springframework.r2dbc: ${SPRING_R2DBC_LOGGING_LEVEL:DEBUG}
    io.r2dbc.postgresql.QUERY: ${POSTGRES_QUERY_LOGGING_LEVEL:DEBUG}
    io.r2dbc.postgresql.PARAM: ${POSTGRES_PARAM_LOGGING_LEVEL:DEBUG}
