spring:
  profiles:
    active: ${SPRING_PROFILE:local}

server:
  port: ${BILLING_SERVICE_PORT:8083}

---
spring:
  r2dbc:
    url: r2dbc:pool:postgresql://${POSTGRES_BILLING_URL}/billing
    username: postgres
    password: ${POSTGRES_BILLING_PWD}
    initialization-mode: always
    pool:
      initial-size: 10
      max-size: 30
      max-idle-time: 30m

logging:
  level:
    org.springframework.data.r2dbc: ${LOGGING_LEVEL:DEBUG}
