spring:
  profiles:
    active: ${SPRING_PROFILE:local}

server:
  port: ${BILLING_SERVICE_PORT:8083}

---
spring:
  r2dbc:
    url: r2dbc:pool:postgresql://${POSTGRES_BILLING_URL}/billing
    username: postgres
    password: ${POSTGRES_BILLING_PWD}
    initialization-mode: always
    pool:
      initial-size: 10
      max-size: 30
      max-idle-time: 30m
  data:
    redis:
      repositories:
        enabled: true
  redis:
    host: ${BILLING_REDIS_HOST}
    port: ${BILLING_REDIS_PORT}

logging:
  level:
    org.springframework.r2dbc: ${SPRING_R2DBC_LOGGING_LEVEL:DEBUG}
    io.r2dbc.postgresql.QUERY: ${POSTGRES_QUERY_LOGGING_LEVEL:DEBUG}
    io.r2dbc.postgresql.PARAM: ${POSTGRES_PARAM_LOGGING_LEVEL:DEBUG}
